// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzi4LbqUE3xtBYpvKaUnvFTyFg4hnprJQ',
    appId: '1:253990018664:web:163e1da9c5220858f065dd',
    messagingSenderId: '253990018664',
    projectId: 'notas-notifica',
    authDomain: 'notas-notifica.firebaseapp.com',
    storageBucket: 'notas-notifica.appspot.com',
    measurementId: 'G-BM7F330Y33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-mLwm_D-k3ASec9BrIT9K5ogXU5Bvv-A',
    appId: '1:253990018664:android:2b9c33ddab62fdebf065dd',
    messagingSenderId: '253990018664',
    projectId: 'notas-notifica',
    storageBucket: 'notas-notifica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX-HBbP2CXF80VkZWe-d3waVN5-CXUeXI',
    appId: '1:253990018664:ios:bcb9a0edda27dfc1f065dd',
    messagingSenderId: '253990018664',
    projectId: 'notas-notifica',
    storageBucket: 'notas-notifica.appspot.com',
    iosClientId: '253990018664-0iihbukc2lbuqu6ag8oqlblsa6p0i5kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.notasNotificacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX-HBbP2CXF80VkZWe-d3waVN5-CXUeXI',
    appId: '1:253990018664:ios:bcb9a0edda27dfc1f065dd',
    messagingSenderId: '253990018664',
    projectId: 'notas-notifica',
    storageBucket: 'notas-notifica.appspot.com',
    iosClientId: '253990018664-0iihbukc2lbuqu6ag8oqlblsa6p0i5kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.notasNotificacion',
  );
}
